name: Publish Snapshot

on:
  workflow_call: {}
  workflow_dispatch:
    inputs:
      snapshot:
        description: "The snapshot to publish"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: snapshot-${{ inputs.snapshot }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Get kubectl version
        run: |
          source hack/lib/kubectl-version.sh
          echo "Using kubectl ${KUBECTL_VERSION}"
          echo "KUBECTL_VERSION=$KUBECTL_VERSION" >> $GITHUB_ENV
      - uses: azure/setup-kubectl@v4
        with:
          version: "${{ env.KUBECTL_VERSION }}"
        id: install
      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-duration-seconds: 900
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GithubActionsSession-publish
      - name: Run publish
        env:
          SNAPSHOT_BUCKET: "${{ secrets.SNAPSHOT_BUCKET }}"
          SNAPSHOT_CLOUDFRONT: "${{ secrets.SNAPSHOT_CLOUDFRONT }}"
          SNAPSHOT: snapshot-${{ inputs.snapshot }}
        run: |
          bash hack/publish-snapshot.sh
